# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170811_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='read_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
